/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,jsx,js}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
      },
      colors: {
        light: {
          primary: "#2563EB",
          surfaceTint: "#2563EB",
          onPrimary: "#FFFFFF",
          primaryContainer: "#DBEAFE",
          onPrimaryContainer: "#1E3A8A",
          secondary: "#475569",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#F1F5F9",
          onSecondaryContainer: "#0F172A",
          tertiary: "#0EA5E9",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#E0F2FE",
          onTertiaryContainer: "#0C4A6E",
          error: "#BA1A1A",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD6",
          onErrorContainer: "#410002",
          background: "#F8FAFC",
          onBackground: "#0F172A",
          surface: "#F8FAFC",
          onSurface: "#0F172A",
          surfaceVariant: "#E2E8F0",
          onSurfaceVariant: "#475569",
          outline: "#64748B",
          outlineVariant: "#CBD5E1",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#334155",
          inverseOnSurface: "#F1F5F9",
          inversePrimary: "#60A5FA",
          primaryFixed: "#DBEAFE",
          onPrimaryFixed: "#1E3A8A",
          primaryFixedDim: "#60A5FA",
          onPrimaryFixedVariant: "#1D4ED8",
          secondaryFixed: "#F1F5F9",
          onSecondaryFixed: "#0F172A",
          secondaryFixedDim: "#94A3B8",
          onSecondaryFixedVariant: "#334155",
          tertiaryFixed: "#E0F2FE",
          onTertiaryFixed: "#0C4A6E",
          tertiaryFixedDim: "#38BDF8",
          onTertiaryFixedVariant: "#0369A1",
          surfaceDim: "#CBD5E1",
          surfaceBright: "#F8FAFC",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F1F5F9",
          surfaceContainer: "#E2E8F0",
          surfaceContainerHigh: "#E2E8F0",
          surfaceContainerHighest: "#CBD5E1",
        },
        dark: {
          primary: "#60A5FA",
          surfaceTint: "#60A5FA",
          onPrimary: "#172554",
          primaryContainer: "#1E40AF",
          onPrimaryContainer: "#DBEAFE",
          secondary: "#94A3B8",
          onSecondary: "#0F172A",
          secondaryContainer: "#334155",
          onSecondaryContainer: "#E2E8F0",
          tertiary: "#38BDF8",
          onTertiary: "#082F49",
          tertiaryContainer: "#0369A1",
          onTertiaryContainer: "#E0F2FE",
          error: "#FFB4AB",
          onError: "#690005",
          errorContainer: "#93000A",
          onErrorContainer: "#FFDAD6",
          background: "#020617",
          onBackground: "#E2E8F0",
          surface: "#020617",
          onSurface: "#E2E8F0",
          surfaceVariant: "#475569",
          onSurfaceVariant: "#94A3B8",
          outline: "#64748B",
          outlineVariant: "#475569",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E2E8F0",
          inverseOnSurface: "#0F172A",
          inversePrimary: "#2563EB",
          primaryFixed: "#DBEAFE",
          onPrimaryFixed: "#1E3A8A",
          primaryFixedDim: "#60A5FA",
          onPrimaryFixedVariant: "#1D4ED8",
          secondaryFixed: "#F1F5F9",
          onSecondaryFixed: "#0F172A",
          secondaryFixedDim: "#94A3B8",
          onSecondaryFixedVariant: "#334155",
          tertiaryFixed: "#E0F2FE",
          onTertiaryFixed: "#0C4A6E",
          tertiaryFixedDim: "#38BDF8",
          onTertiaryFixedVariant: "#0369A1",
          surfaceDim: "#020617",
          surfaceBright: "#1E293B",
          surfaceContainerLowest: "#000000",
          surfaceContainerLow: "#0F172A",
          surfaceContainer: "#1E293B",
          surfaceContainerHigh: "#334155",
          surfaceContainerHighest: "#475569",
        },
      },
      space: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        13: "52px",
        14: "56px",
        15: "60px",
        16: "64px",
        17: "68px",
        18: "72px",
        19: "76px",
        20: "80px",
        21: "84px",
        22: "88px",
        23: "92px",
        24: "96px",
        25: "100px",
        26: "104px",
        27: "108px",
        28: "112px",
        29: "116px",
        30: "120px",
      },
      boxShadow: {
        elevation1:
          "0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)",
        elevation2:
          "0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)",
        elevation3:
          "0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)",
        elevation4:
          "0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)",
        elevation5:
          "0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)",
      },
      borderRadius: {
        none: "0",
        extraSmall: "4px",
        small: "8px",
        medium: "12px",
        large: "16px",
        extraLarge: "28px",
        full: "1000px",
      },
      fontSize: {
        displayLarge: [
          "57px",
          {
            fontWeight: "400",
            lineHeight: "64px",
            letterSpacing: "-0.25px",
          },
        ],
        displayMedium: [
          "45px",
          {
            fontWeight: "400",
            lineHeight: "52px",
            letterSpacing: "0",
          },
        ],
        displaySmall: [
          "36px",
          {
            fontWeight: "400",
            lineHeight: "44px",
            letterSpacing: "0",
          },
        ],
        headlineLarge: [
          "32px",
          {
            fontWeight: "400",
            lineHeight: "40px",
            letterSpacing: "0",
          },
        ],
        headlineMedium: [
          "28px",
          {
            fontWeight: "400",
            lineHeight: "36px",
            letterSpacing: "0",
          },
        ],
        headlineSmall: [
          "24px",
          {
            fontWeight: "400",
            lineHeight: "32px",
            letterSpacing: "0",
          },
        ],
        titleLarge: [
          "22px",
          {
            fontWeight: "400",
            lineHeight: "28px",
            letterSpacing: "0",
          },
        ],
        titleMedium: [
          "16px",
          {
            fontWeight: "500",
            lineHeight: "24px",
            letterSpacing: "0.15px",
          },
        ],
        titleSmall: [
          "14px",
          {
            fontWeight: "500",
            lineHeight: "20px",
            letterSpacing: "0.1px",
          },
        ],
        bodyLarge: [
          "16px",
          {
            fontWeight: "400",
            lineHeight: "24px",
            letterSpacing: "0.5px",
          },
        ],
        bodyMedium: [
          "14px",
          {
            fontWeight: "400",
            lineHeight: "20px",
            letterSpacing: "0.25px",
          },
        ],
        bodySmall: [
          "12px",
          {
            fontWeight: "400",
            lineHeight: "16px",
            letterSpacing: "0.4px",
          },
        ],
        labelLarge: [
          "14px",
          {
            fontWeight: "500",
            lineHeight: "20px",
            letterSpacing: "0.1px",
          },
        ],
        labelMedium: [
          "12px",
          {
            fontWeight: "500",
            lineHeight: "16px",
            letterSpacing: "0.5px",
          },
        ],
        labelSmall: [
          "11px",
          {
            fontWeight: "500",
            lineHeight: "16px",
            letterSpacing: "0.5px",
          },
        ],
      },
      transitionDuration: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
        extraLong1: "700ms",
        extraLong2: "800ms",
        extraLong3: "900ms",
        extraLong4: "1000ms",
      },
      transitionDelay: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
        extraLong1: "700ms",
        extraLong2: "800ms",
        extraLong3: "900ms",
        extraLong4: "1000ms",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        standardDecelerate: "cubic-bezier(0, 0, 0, 1)",
        standardAccelerate: "cubic-bezier(0.3, 0, 1, 1)",
        emphasized: "cubic-bezier(0.2, 0, 0, 1.0)",
        emphasizedDecelerate: "cubic-bezier(0.05, 0.7, 0.1, 1)",
        emphasizedAccelerate: "cubic-bezier(0.3, 0, 0.8, 0.15)",
        legacy: "cubic-bezier(0.4, 0, 0.2, 1.0)",
        legacyDecelerate: "cubic-bezier(0, 0, 0.2, 1)",
        legacyAccelerate: "cubic-bezier(0.4, 0, 1, 1)",
        linear: "cubic-bezier(0, 0, 1, 1)",
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          '0%': { opacity: '0', transform: 'translateX(10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0px)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'fade-in-down': 'fadeInDown 0.5s ease-out',
        'fade-in-left': 'fadeInLeft 0.8s ease-out',
        'blob': 'blob 7s infinite',
        'float': 'float 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
